FROM node:12.18.4 
WORKDIR /usr/src/server
COPY ./server/package*.json ./
RUN npm install
EXPOSE 3000

# Add docker-compose-wait tool -------------------
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait