FROM nginx:latest
WORKDIR /usr/share/nginx/html
RUN rm -rf /usr/share/nginx/html/*
COPY ./docker/logs/ /usr/share/nginx/
ENTRYPOINT /bin/bash -x /usr/share/nginx/logs-init.sh && nginx -g 'daemon off;' 